#include "cg/sys/opengl.h"

#include <cassert>
#include <windows.h>
#include "cg/base/base.h"

namespace {

extern "C" using func_t = void(*);

inline func_t load_dll_func(HMODULE dll, const char* func_name)
{
	assert(dll);
	assert(func_name);

	func_t f = static_cast<func_t>(GetProcAddress(dll, func_name));
	cg::enforce(f, func_name);
	
	return f;
}

inline func_t load_opengl_func(const char* func_name)
{
	assert(func_name);

	func_t f = static_cast<func_t>(wglGetProcAddress(func_name));
	cg::enforce(f, func_name);

	return f;
}

} // namespace

namespace cg {
namespace sys {

Opengl_render_context::Opengl_render_context(HWND hwnd)
	: _hwnd(hwnd)
{
	assert(_hwnd);

	_hdc = GetDC(_hwnd);
	assert(_hdc);

	PIXELFORMATDESCRIPTOR pixel_fmt_desc = {};
	pixel_fmt_desc.nSize = sizeof(PIXELFORMATDESCRIPTOR);
	pixel_fmt_desc.nVersion = 1;
	pixel_fmt_desc.dwFlags = PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER;
	pixel_fmt_desc.iPixelType = PFD_TYPE_RGBA;
	pixel_fmt_desc.cColorBits = 32;
	pixel_fmt_desc.cDepthBits = 32;
	pixel_fmt_desc.iLayerType = PFD_MAIN_PLANE;

	int pixel_format = ChoosePixelFormat(_hdc, &pixel_fmt_desc);
	assert(pixel_format > 0);
	SetPixelFormat(_hdc, pixel_format, &pixel_fmt_desc);

	_hglrc = wglCreateContext(_hdc);
	assert(_hglrc);
	wglMakeCurrent(_hdc, _hglrc);

	// load opengl funcs
	_opengl_dll = LoadLibrary("opengl32.dll");
	load_opengl_11();

	glGetIntegerv(GL_MAJOR_VERSION, &_version_major);
	glGetIntegerv(GL_MINOR_VERSION, &_version_minor);
	enforce(_version_major == 4 && _version_minor == 5, "Opengl version must be 4.5 or greater.");
	load_opengl_45();
}

Opengl_render_context::~Opengl_render_context() noexcept
{
	if (_opengl_dll) {
		FreeLibrary(_opengl_dll);
		_opengl_dll = nullptr;
	}

	if (_hglrc) {
		wglMakeCurrent(_hdc, nullptr);
		wglDeleteContext(_hglrc);
		_hglrc = nullptr;
	}

	if (_hdc) {
		ReleaseDC(_hwnd, _hdc);
		_hdc = nullptr;
	}
}

void Opengl_render_context::load_opengl_11() const
{
	// opengl 1.0
	glCullFace = static_cast<PFNGLCULLFACEPROC>(load_dll_func(_opengl_dll, "glCullFace"));
	glFrontFace = static_cast<PFNGLFRONTFACEPROC>(load_dll_func(_opengl_dll, "glFrontFace"));
	glHint = static_cast<PFNGLHINTPROC>(load_dll_func(_opengl_dll, "glHint"));
	glLineWidth = static_cast<PFNGLLINEWIDTHPROC>(load_dll_func(_opengl_dll, "glLineWidth"));
	glPointSize = static_cast<PFNGLPOINTSIZEPROC>(load_dll_func(_opengl_dll, "glPointSize"));
	glPolygonMode = static_cast<PFNGLPOLYGONMODEPROC>(load_dll_func(_opengl_dll, "glPolygonMode"));
	glScissor = static_cast<PFNGLSCISSORPROC>(load_dll_func(_opengl_dll, "glScissor"));
	glTexParameterf = static_cast<PFNGLTEXPARAMETERFPROC>(load_dll_func(_opengl_dll, "glTexParameterf"));
	glTexParameterfv = static_cast<PFNGLTEXPARAMETERFVPROC>(load_dll_func(_opengl_dll, "glTexParameterfv"));
	glTexParameteri = static_cast<PFNGLTEXPARAMETERIPROC>(load_dll_func(_opengl_dll, "glTexParameteri"));
	glTexParameteriv = static_cast<PFNGLTEXPARAMETERIVPROC>(load_dll_func(_opengl_dll, "glTexParameteriv"));
	glTexImage1D = static_cast<PFNGLTEXIMAGE1DPROC>(load_dll_func(_opengl_dll, "glTexImage1D"));
	glTexImage2D = static_cast<PFNGLTEXIMAGE2DPROC>(load_dll_func(_opengl_dll, "glTexImage2D"));
	glClear = static_cast<PFNGLCLEARPROC>(load_dll_func(_opengl_dll, "glClear"));
	glClearColor = static_cast<PFNGLCLEARCOLORPROC>(load_dll_func(_opengl_dll, "glClearColor"));
	glClearStencil = static_cast<PFNGLCLEARSTENCILPROC>(load_dll_func(_opengl_dll, "glClearStencil"));
	glClearDepth = static_cast<PFNGLCLEARDEPTHPROC>(load_dll_func(_opengl_dll, "glClearDepth"));
	glStencilMask = static_cast<PFNGLSTENCILMASKPROC>(load_dll_func(_opengl_dll, "glStencilMask"));
	glColorMask = static_cast<PFNGLCOLORMASKPROC>(load_dll_func(_opengl_dll, "glColorMask"));
	glDepthMask = static_cast<PFNGLDEPTHMASKPROC>(load_dll_func(_opengl_dll, "glDepthMask"));
	glDisable = static_cast<PFNGLDISABLEPROC>(load_dll_func(_opengl_dll, "glDisable"));
	glEnable = static_cast<PFNGLENABLEPROC>(load_dll_func(_opengl_dll, "glEnable"));
	glFinish = static_cast<PFNGLFINISHPROC>(load_dll_func(_opengl_dll, "glFinish"));
	glFlush = static_cast<PFNGLFLUSHPROC>(load_dll_func(_opengl_dll, "glFlush"));
	glBlendFunc = static_cast<PFNGLBLENDFUNCPROC>(load_dll_func(_opengl_dll, "glBlendFunc"));
	glLogicOp = static_cast<PFNGLLOGICOPPROC>(load_dll_func(_opengl_dll, "glLogicOp"));
	glStencilFunc = static_cast<PFNGLSTENCILFUNCPROC>(load_dll_func(_opengl_dll, "glStencilFunc"));
	glStencilOp = static_cast<PFNGLSTENCILOPPROC>(load_dll_func(_opengl_dll, "glStencilOp"));
	glDepthFunc = static_cast<PFNGLDEPTHFUNCPROC>(load_dll_func(_opengl_dll, "glDepthFunc"));
	glPixelStoref = static_cast<PFNGLPIXELSTOREFPROC>(load_dll_func(_opengl_dll, "glPixelStoref"));
	glPixelStorei = static_cast<PFNGLPIXELSTOREIPROC>(load_dll_func(_opengl_dll, "glPixelStorei"));
	glReadBuffer = static_cast<PFNGLREADBUFFERPROC>(load_dll_func(_opengl_dll, "glReadBuffer"));
	glReadPixels = static_cast<PFNGLREADPIXELSPROC>(load_dll_func(_opengl_dll, "glReadPixels"));
	glGetBooleanv = static_cast<PFNGLGETBOOLEANVPROC>(load_dll_func(_opengl_dll, "glGetBooleanv"));
	glGetDoublev = static_cast<PFNGLGETDOUBLEVPROC>(load_dll_func(_opengl_dll, "glGetDoublev"));
	glGetError = static_cast<PFNGLGETERRORPROC>(load_dll_func(_opengl_dll, "glGetError"));
	glGetFloatv = static_cast<PFNGLGETFLOATVPROC>(load_dll_func(_opengl_dll, "glGetFloatv"));
	glGetIntegerv = static_cast<PFNGLGETINTEGERVPROC>(load_dll_func(_opengl_dll, "glGetIntegerv"));
	glGetString = static_cast<PFNGLGETSTRINGPROC>(load_dll_func(_opengl_dll, "glGetString"));
	glGetTexImage = static_cast<PFNGLGETTEXIMAGEPROC>(load_dll_func(_opengl_dll, "glGetTexImage"));
	glGetTexParameterfv = static_cast<PFNGLGETTEXPARAMETERFVPROC>(load_dll_func(_opengl_dll, "glGetTexParameterfv"));
	glGetTexParameteriv = static_cast<PFNGLGETTEXPARAMETERIVPROC>(load_dll_func(_opengl_dll, "glGetTexParameteriv"));
	glGetTexLevelParameterfv = static_cast<PFNGLGETTEXLEVELPARAMETERFVPROC>(load_dll_func(_opengl_dll, "glGetTexLevelParameterfv"));
	glGetTexLevelParameteriv = static_cast<PFNGLGETTEXLEVELPARAMETERIVPROC>(load_dll_func(_opengl_dll, "glGetTexLevelParameteriv"));
	glIsEnabled = static_cast<PFNGLISENABLEDPROC>(load_dll_func(_opengl_dll, "glIsEnabled"));
	glDepthRange = static_cast<PFNGLDEPTHRANGEPROC>(load_dll_func(_opengl_dll, "glDepthRange"));
	glViewport = static_cast<PFNGLVIEWPORTPROC>(load_dll_func(_opengl_dll, "glViewport"));
	// opengl 1.1
	glDrawArrays = static_cast<PFNGLDRAWARRAYSPROC>(load_dll_func(_opengl_dll, "glDrawArrays"));
	glDrawElements = static_cast<PFNGLDRAWELEMENTSPROC>(load_dll_func(_opengl_dll, "glDrawElements"));
	glGetPointerv = static_cast<PFNGLGETPOINTERVPROC>(load_dll_func(_opengl_dll, "glGetPointerv"));
	glPolygonOffset = static_cast<PFNGLPOLYGONOFFSETPROC>(load_dll_func(_opengl_dll, "glPolygonOffset"));
	glCopyTexImage1D = static_cast<PFNGLCOPYTEXIMAGE1DPROC>(load_dll_func(_opengl_dll, "glCopyTexImage1D"));
	glCopyTexImage2D = static_cast<PFNGLCOPYTEXIMAGE2DPROC>(load_dll_func(_opengl_dll, "glCopyTexImage2D"));
	glCopyTexSubImage1D = static_cast<PFNGLCOPYTEXSUBIMAGE1DPROC>(load_dll_func(_opengl_dll, "glCopyTexSubImage1D"));
	glCopyTexSubImage2D = static_cast<PFNGLCOPYTEXSUBIMAGE2DPROC>(load_dll_func(_opengl_dll, "glCopyTexSubImage2D"));
	glTexSubImage1D = static_cast<PFNGLTEXSUBIMAGE1DPROC>(load_dll_func(_opengl_dll, "glTexSubImage1D"));
	glTexSubImage2D = static_cast<PFNGLTEXSUBIMAGE2DPROC>(load_dll_func(_opengl_dll, "glTexSubImage2D"));
	glBindTexture = static_cast<PFNGLBINDTEXTUREPROC>(load_dll_func(_opengl_dll, "glBindTexture"));
	glDeleteTextures = static_cast<PFNGLDELETETEXTURESPROC>(load_dll_func(_opengl_dll, "glDeleteTextures"));
	glGenTextures = static_cast<PFNGLGENTEXTURESPROC>(load_dll_func(_opengl_dll, "glGenTextures"));
	glIsTexture = static_cast<PFNGLISTEXTUREPROC>(load_dll_func(_opengl_dll, "glIsTexture"));
}

void Opengl_render_context::load_opengl_45() const
{
	// opengl 1.2
	glDrawRangeElements = static_cast<PFNGLDRAWRANGEELEMENTSPROC>(load_opengl_func("glDrawRangeElements"));
	glTexImage3D = static_cast<PFNGLTEXIMAGE3DPROC>(load_opengl_func("glTexImage3D"));
	glTexSubImage3D = static_cast<PFNGLTEXSUBIMAGE3DPROC>(load_opengl_func("glTexSubImage3D"));
	glCopyTexSubImage3D = static_cast<PFNGLCOPYTEXSUBIMAGE3DPROC>(load_opengl_func("glCopyTexSubImage3D"));
	// opengl 1.3
	glActiveTexture = static_cast<PFNGLACTIVETEXTUREPROC>(load_opengl_func("glActiveTexture"));
	glSampleCoverage = static_cast<PFNGLSAMPLECOVERAGEPROC>(load_opengl_func("glSampleCoverage"));
	glCompressedTexImage3D = static_cast<PFNGLCOMPRESSEDTEXIMAGE3DPROC>(load_opengl_func("glCompressedTexImage3D"));
	glCompressedTexImage2D = static_cast<PFNGLCOMPRESSEDTEXIMAGE2DPROC>(load_opengl_func("glCompressedTexImage2D"));
	glCompressedTexImage1D = static_cast<PFNGLCOMPRESSEDTEXIMAGE1DPROC>(load_opengl_func("glCompressedTexImage1D"));
	glCompressedTexSubImage3D = static_cast<PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC>(load_opengl_func("glCompressedTexSubImage3D"));
	glCompressedTexSubImage2D = static_cast<PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC>(load_opengl_func("glCompressedTexSubImage2D"));
	glCompressedTexSubImage1D = static_cast<PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC>(load_opengl_func("glCompressedTexSubImage1D"));
	glGetCompressedTexImage = static_cast<PFNGLGETCOMPRESSEDTEXIMAGEPROC>(load_opengl_func("glGetCompressedTexImage"));
	// opengl 1.4
	glBlendFuncSeparate = static_cast<PFNGLBLENDFUNCSEPARATEPROC>(load_opengl_func("glBlendFuncSeparate"));
	glMultiDrawArrays = static_cast<PFNGLMULTIDRAWARRAYSPROC>(load_opengl_func("glMultiDrawArrays"));
	glMultiDrawElements = static_cast<PFNGLMULTIDRAWELEMENTSPROC>(load_opengl_func("glMultiDrawElements"));
	glPointParameterf = static_cast<PFNGLPOINTPARAMETERFPROC>(load_opengl_func("glPointParameterf"));
	glPointParameterfv = static_cast<PFNGLPOINTPARAMETERFVPROC>(load_opengl_func("glPointParameterfv"));
	glPointParameteri = static_cast<PFNGLPOINTPARAMETERIPROC>(load_opengl_func("glPointParameteri"));
	glPointParameteriv = static_cast<PFNGLPOINTPARAMETERIVPROC>(load_opengl_func("glPointParameteriv"));
	glBlendColor = static_cast<PFNGLBLENDCOLORPROC>(load_opengl_func("glBlendColor"));
	glBlendEquation = static_cast<PFNGLBLENDEQUATIONPROC>(load_opengl_func("glBlendEquation"));
	// opengl 1.5
	glGenQueries = static_cast<PFNGLGENQUERIESPROC>(load_opengl_func("glGenQueries"));
	glDeleteQueries = static_cast<PFNGLDELETEQUERIESPROC>(load_opengl_func("glDeleteQueries"));
	glIsQuery = static_cast<PFNGLISQUERYPROC>(load_opengl_func("glIsQuery"));
	glBeginQuery = static_cast<PFNGLBEGINQUERYPROC>(load_opengl_func("glBeginQuery"));
	glEndQuery = static_cast<PFNGLENDQUERYPROC>(load_opengl_func("glEndQuery"));
	glGetQueryiv = static_cast<PFNGLGETQUERYIVPROC>(load_opengl_func("glGetQueryiv"));
	glGetQueryObjectiv = static_cast<PFNGLGETQUERYOBJECTIVPROC>(load_opengl_func("glGetQueryObjectiv"));
	glGetQueryObjectuiv = static_cast<PFNGLGETQUERYOBJECTUIVPROC>(load_opengl_func("glGetQueryObjectuiv"));
	glDeleteBuffers = static_cast<PFNGLDELETEBUFFERSPROC>(load_opengl_func("glDeleteBuffers"));
	glGenBuffers = static_cast<PFNGLGENBUFFERSPROC>(load_opengl_func("glGenBuffers"));
	glIsBuffer = static_cast<PFNGLISBUFFERPROC>(load_opengl_func("glIsBuffer"));
	glBufferData = static_cast<PFNGLBUFFERDATAPROC>(load_opengl_func("glBufferData"));
	glBufferSubData = static_cast<PFNGLBUFFERSUBDATAPROC>(load_opengl_func("glBufferSubData"));
	glGetBufferSubData = static_cast<PFNGLGETBUFFERSUBDATAPROC>(load_opengl_func("glGetBufferSubData"));
	glMapBuffer = static_cast<PFNGLMAPBUFFERPROC>(load_opengl_func("glMapBuffer"));
	glUnmapBuffer = static_cast<PFNGLUNMAPBUFFERPROC>(load_opengl_func("glUnmapBuffer"));
	glGetBufferParameteriv = static_cast<PFNGLGETBUFFERPARAMETERIVPROC>(load_opengl_func("glGetBufferParameteriv"));
	glGetBufferPointerv = static_cast<PFNGLGETBUFFERPOINTERVPROC>(load_opengl_func("glGetBufferPointerv"));
	// opengl 2.0
	glBlendEquationSeparate = static_cast<PFNGLBLENDEQUATIONSEPARATEPROC>(load_opengl_func("glBlendEquationSeparate"));
	glDrawBuffers = static_cast<PFNGLDRAWBUFFERSPROC>(load_opengl_func("glDrawBuffers"));
	glStencilOpSeparate = static_cast<PFNGLSTENCILOPSEPARATEPROC>(load_opengl_func("glStencilOpSeparate"));
	glStencilFuncSeparate = static_cast<PFNGLSTENCILFUNCSEPARATEPROC>(load_opengl_func("glStencilFuncSeparate"));
	glStencilMaskSeparate = static_cast<PFNGLSTENCILMASKSEPARATEPROC>(load_opengl_func("glStencilMaskSeparate"));
	glAttachShader = static_cast<PFNGLATTACHSHADERPROC>(load_opengl_func("glAttachShader"));
	glBindAttribLocation = static_cast<PFNGLBINDATTRIBLOCATIONPROC>(load_opengl_func("glBindAttribLocation"));
	glCompileShader = static_cast<PFNGLCOMPILESHADERPROC>(load_opengl_func("glCompileShader"));
	glCreateProgram = static_cast<PFNGLCREATEPROGRAMPROC>(load_opengl_func("glCreateProgram"));
	glCreateShader = static_cast<PFNGLCREATESHADERPROC>(load_opengl_func("glCreateShader"));
	glDeleteProgram = static_cast<PFNGLDELETEPROGRAMPROC>(load_opengl_func("glDeleteProgram"));
	glDeleteShader = static_cast<PFNGLDELETESHADERPROC>(load_opengl_func("glDeleteShader"));
	glDetachShader = static_cast<PFNGLDETACHSHADERPROC>(load_opengl_func("glDetachShader"));
	glDisableVertexAttribArray = static_cast<PFNGLDISABLEVERTEXATTRIBARRAYPROC>(load_opengl_func("glDisableVertexAttribArray"));
	glEnableVertexAttribArray = static_cast<PFNGLENABLEVERTEXATTRIBARRAYPROC>(load_opengl_func("glEnableVertexAttribArray"));
	glGetActiveAttrib = static_cast<PFNGLGETACTIVEATTRIBPROC>(load_opengl_func("glGetActiveAttrib"));
	glGetActiveUniform = static_cast<PFNGLGETACTIVEUNIFORMPROC>(load_opengl_func("glGetActiveUniform"));
	glGetAttachedShaders = static_cast<PFNGLGETATTACHEDSHADERSPROC>(load_opengl_func("glGetAttachedShaders"));
	glGetAttribLocation = static_cast<PFNGLGETATTRIBLOCATIONPROC>(load_opengl_func("glGetAttribLocation"));
	glGetProgramiv = static_cast<PFNGLGETPROGRAMIVPROC>(load_opengl_func("glGetProgramiv"));
	glGetProgramInfoLog = static_cast<PFNGLGETPROGRAMINFOLOGPROC>(load_opengl_func("glGetProgramInfoLog"));
	glGetShaderiv = static_cast<PFNGLGETSHADERIVPROC>(load_opengl_func("glGetShaderiv"));
	glGetShaderInfoLog = static_cast<PFNGLGETSHADERINFOLOGPROC>(load_opengl_func("glGetShaderInfoLog"));
	glGetShaderSource = static_cast<PFNGLGETSHADERSOURCEPROC>(load_opengl_func("glGetShaderSource"));
	glGetUniformLocation = static_cast<PFNGLGETUNIFORMLOCATIONPROC>(load_opengl_func("glGetUniformLocation"));
	glGetUniformfv = static_cast<PFNGLGETUNIFORMFVPROC>(load_opengl_func("glGetUniformfv"));
	glGetUniformiv = static_cast<PFNGLGETUNIFORMIVPROC>(load_opengl_func("glGetUniformiv"));
	glGetVertexAttribdv = static_cast<PFNGLGETVERTEXATTRIBDVPROC>(load_opengl_func("glGetVertexAttribdv"));
	glGetVertexAttribfv = static_cast<PFNGLGETVERTEXATTRIBFVPROC>(load_opengl_func("glGetVertexAttribfv"));
	glGetVertexAttribiv = static_cast<PFNGLGETVERTEXATTRIBIVPROC>(load_opengl_func("glGetVertexAttribiv"));
	glGetVertexAttribPointerv = static_cast<PFNGLGETVERTEXATTRIBPOINTERVPROC>(load_opengl_func("glGetVertexAttribPointerv"));
	glIsProgram = static_cast<PFNGLISPROGRAMPROC>(load_opengl_func("glIsProgram"));
	glIsShader = static_cast<PFNGLISSHADERPROC>(load_opengl_func("glIsShader"));
	glLinkProgram = static_cast<PFNGLLINKPROGRAMPROC>(load_opengl_func("glLinkProgram"));
	glShaderSource = static_cast<PFNGLSHADERSOURCEPROC>(load_opengl_func("glShaderSource"));
	glUseProgram = static_cast<PFNGLUSEPROGRAMPROC>(load_opengl_func("glUseProgram"));
	glUniform1f = static_cast<PFNGLUNIFORM1FPROC>(load_opengl_func("glUniform1f"));
	glUniform2f = static_cast<PFNGLUNIFORM2FPROC>(load_opengl_func("glUniform2f"));
	glUniform3f = static_cast<PFNGLUNIFORM3FPROC>(load_opengl_func("glUniform3f"));
	glUniform4f = static_cast<PFNGLUNIFORM4FPROC>(load_opengl_func("glUniform4f"));
	glUniform1i = static_cast<PFNGLUNIFORM1IPROC>(load_opengl_func("glUniform1i"));
	glUniform2i = static_cast<PFNGLUNIFORM2IPROC>(load_opengl_func("glUniform2i"));
	glUniform3i = static_cast<PFNGLUNIFORM3IPROC>(load_opengl_func("glUniform3i"));
	glUniform4i = static_cast<PFNGLUNIFORM4IPROC>(load_opengl_func("glUniform4i"));
	glUniform1fv = static_cast<PFNGLUNIFORM1FVPROC>(load_opengl_func("glUniform1fv"));
	glUniform2fv = static_cast<PFNGLUNIFORM2FVPROC>(load_opengl_func("glUniform2fv"));
	glUniform3fv = static_cast<PFNGLUNIFORM3FVPROC>(load_opengl_func("glUniform3fv"));
	glUniform4fv = static_cast<PFNGLUNIFORM4FVPROC>(load_opengl_func("glUniform4fv"));
	glUniform1iv = static_cast<PFNGLUNIFORM1IVPROC>(load_opengl_func("glUniform1iv"));
	glUniform2iv = static_cast<PFNGLUNIFORM2IVPROC>(load_opengl_func("glUniform2iv"));
	glUniform3iv = static_cast<PFNGLUNIFORM3IVPROC>(load_opengl_func("glUniform3iv"));
	glUniform4iv = static_cast<PFNGLUNIFORM4IVPROC>(load_opengl_func("glUniform4iv"));
	glUniformMatrix2fv = static_cast<PFNGLUNIFORMMATRIX2FVPROC>(load_opengl_func("glUniformMatrix2fv"));
	glUniformMatrix3fv = static_cast<PFNGLUNIFORMMATRIX3FVPROC>(load_opengl_func("glUniformMatrix3fv"));
	glUniformMatrix4fv = static_cast<PFNGLUNIFORMMATRIX4FVPROC>(load_opengl_func("glUniformMatrix4fv"));
	glValidateProgram = static_cast<PFNGLVALIDATEPROGRAMPROC>(load_opengl_func("glValidateProgram"));
	glVertexAttrib1d = static_cast<PFNGLVERTEXATTRIB1DPROC>(load_opengl_func("glVertexAttrib1d"));
	glVertexAttrib1dv = static_cast<PFNGLVERTEXATTRIB1DVPROC>(load_opengl_func("glVertexAttrib1dv"));
	glVertexAttrib1f = static_cast<PFNGLVERTEXATTRIB1FPROC>(load_opengl_func("glVertexAttrib1f"));
	glVertexAttrib1fv = static_cast<PFNGLVERTEXATTRIB1FVPROC>(load_opengl_func("glVertexAttrib1fv"));
	glVertexAttrib1s = static_cast<PFNGLVERTEXATTRIB1SPROC>(load_opengl_func("glVertexAttrib1s"));
	glVertexAttrib1sv = static_cast<PFNGLVERTEXATTRIB1SVPROC>(load_opengl_func("glVertexAttrib1sv"));
	glVertexAttrib2d = static_cast<PFNGLVERTEXATTRIB2DPROC>(load_opengl_func("glVertexAttrib2d"));
	glVertexAttrib2dv = static_cast<PFNGLVERTEXATTRIB2DVPROC>(load_opengl_func("glVertexAttrib2dv"));
	glVertexAttrib2f = static_cast<PFNGLVERTEXATTRIB2FPROC>(load_opengl_func("glVertexAttrib2f"));
	glVertexAttrib2fv = static_cast<PFNGLVERTEXATTRIB2FVPROC>(load_opengl_func("glVertexAttrib2fv"));
	glVertexAttrib2s = static_cast<PFNGLVERTEXATTRIB2SPROC>(load_opengl_func("glVertexAttrib2s"));
	glVertexAttrib2sv = static_cast<PFNGLVERTEXATTRIB2SVPROC>(load_opengl_func("glVertexAttrib2sv"));
	glVertexAttrib3d = static_cast<PFNGLVERTEXATTRIB3DPROC>(load_opengl_func("glVertexAttrib3d"));
	glVertexAttrib3dv = static_cast<PFNGLVERTEXATTRIB3DVPROC>(load_opengl_func("glVertexAttrib3dv"));
	glVertexAttrib3f = static_cast<PFNGLVERTEXATTRIB3FPROC>(load_opengl_func("glVertexAttrib3f"));
	glVertexAttrib3fv = static_cast<PFNGLVERTEXATTRIB3FVPROC>(load_opengl_func("glVertexAttrib3fv"));
	glVertexAttrib3s = static_cast<PFNGLVERTEXATTRIB3SPROC>(load_opengl_func("glVertexAttrib3s"));
	glVertexAttrib3sv = static_cast<PFNGLVERTEXATTRIB3SVPROC>(load_opengl_func("glVertexAttrib3sv"));
	glVertexAttrib4Nbv = static_cast<PFNGLVERTEXATTRIB4NBVPROC>(load_opengl_func("glVertexAttrib4Nbv"));
	glVertexAttrib4Niv = static_cast<PFNGLVERTEXATTRIB4NIVPROC>(load_opengl_func("glVertexAttrib4Niv"));
	glVertexAttrib4Nsv = static_cast<PFNGLVERTEXATTRIB4NSVPROC>(load_opengl_func("glVertexAttrib4Nsv"));
	glVertexAttrib4Nub = static_cast<PFNGLVERTEXATTRIB4NUBPROC>(load_opengl_func("glVertexAttrib4Nub"));
	glVertexAttrib4Nubv = static_cast<PFNGLVERTEXATTRIB4NUBVPROC>(load_opengl_func("glVertexAttrib4Nubv"));
	glVertexAttrib4Nuiv = static_cast<PFNGLVERTEXATTRIB4NUIVPROC>(load_opengl_func("glVertexAttrib4Nuiv"));
	glVertexAttrib4Nusv = static_cast<PFNGLVERTEXATTRIB4NUSVPROC>(load_opengl_func("glVertexAttrib4Nusv"));
	glVertexAttrib4bv = static_cast<PFNGLVERTEXATTRIB4BVPROC>(load_opengl_func("glVertexAttrib4bv"));
	glVertexAttrib4d = static_cast<PFNGLVERTEXATTRIB4DPROC>(load_opengl_func("glVertexAttrib4d"));
	glVertexAttrib4dv = static_cast<PFNGLVERTEXATTRIB4DVPROC>(load_opengl_func("glVertexAttrib4dv"));
	glVertexAttrib4f = static_cast<PFNGLVERTEXATTRIB4FPROC>(load_opengl_func("glVertexAttrib4f"));
	glVertexAttrib4fv = static_cast<PFNGLVERTEXATTRIB4FVPROC>(load_opengl_func("glVertexAttrib4fv"));
	glVertexAttrib4iv = static_cast<PFNGLVERTEXATTRIB4IVPROC>(load_opengl_func("glVertexAttrib4iv"));
	glVertexAttrib4s = static_cast<PFNGLVERTEXATTRIB4SPROC>(load_opengl_func("glVertexAttrib4s"));
	glVertexAttrib4sv = static_cast<PFNGLVERTEXATTRIB4SVPROC>(load_opengl_func("glVertexAttrib4sv"));
	glVertexAttrib4ubv = static_cast<PFNGLVERTEXATTRIB4UBVPROC>(load_opengl_func("glVertexAttrib4ubv"));
	glVertexAttrib4uiv = static_cast<PFNGLVERTEXATTRIB4UIVPROC>(load_opengl_func("glVertexAttrib4uiv"));
	glVertexAttrib4usv = static_cast<PFNGLVERTEXATTRIB4USVPROC>(load_opengl_func("glVertexAttrib4usv"));
	glVertexAttribPointer = static_cast<PFNGLVERTEXATTRIBPOINTERPROC>(load_opengl_func("glVertexAttribPointer"));
}

} // namespace sys
} // namespace cg


PFNGLCULLFACEPROC glCullFace;
PFNGLFRONTFACEPROC glFrontFace;
PFNGLHINTPROC glHint;
PFNGLLINEWIDTHPROC glLineWidth;
PFNGLPOINTSIZEPROC glPointSize;
PFNGLPOLYGONMODEPROC glPolygonMode;
PFNGLSCISSORPROC glScissor;
PFNGLTEXPARAMETERFPROC glTexParameterf;
PFNGLTEXPARAMETERFVPROC glTexParameterfv;
PFNGLTEXPARAMETERIPROC glTexParameteri;
PFNGLTEXPARAMETERIVPROC glTexParameteriv;
PFNGLTEXIMAGE1DPROC glTexImage1D;
PFNGLTEXIMAGE2DPROC glTexImage2D;
PFNGLDRAWBUFFERPROC glDrawBuffer;
PFNGLCLEARPROC glClear;
PFNGLCLEARCOLORPROC glClearColor;
PFNGLCLEARSTENCILPROC glClearStencil;
PFNGLCLEARDEPTHPROC glClearDepth;
PFNGLSTENCILMASKPROC glStencilMask;
PFNGLCOLORMASKPROC glColorMask;
PFNGLDEPTHMASKPROC glDepthMask;
PFNGLDISABLEPROC glDisable;
PFNGLENABLEPROC glEnable;
PFNGLFINISHPROC glFinish;
PFNGLFLUSHPROC glFlush;
PFNGLBLENDFUNCPROC glBlendFunc;
PFNGLLOGICOPPROC glLogicOp;
PFNGLSTENCILFUNCPROC glStencilFunc;
PFNGLSTENCILOPPROC glStencilOp;
PFNGLDEPTHFUNCPROC glDepthFunc;
PFNGLPIXELSTOREFPROC glPixelStoref;
PFNGLPIXELSTOREIPROC glPixelStorei;
PFNGLREADBUFFERPROC glReadBuffer;
PFNGLREADPIXELSPROC glReadPixels;
PFNGLGETBOOLEANVPROC glGetBooleanv;
PFNGLGETDOUBLEVPROC glGetDoublev;
PFNGLGETERRORPROC glGetError;
PFNGLGETFLOATVPROC glGetFloatv;
PFNGLGETINTEGERVPROC glGetIntegerv;
PFNGLGETSTRINGPROC glGetString;
PFNGLGETTEXIMAGEPROC glGetTexImage;
PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
PFNGLISENABLEDPROC glIsEnabled;
PFNGLDEPTHRANGEPROC glDepthRange;
PFNGLVIEWPORTPROC glViewport;
PFNGLDRAWARRAYSPROC glDrawArrays;
PFNGLDRAWELEMENTSPROC glDrawElements;
PFNGLGETPOINTERVPROC glGetPointerv;
PFNGLPOLYGONOFFSETPROC glPolygonOffset;
PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D;
PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D;
PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
PFNGLBINDTEXTUREPROC glBindTexture;
PFNGLDELETETEXTURESPROC glDeleteTextures;
PFNGLGENTEXTURESPROC glGenTextures;
PFNGLISTEXTUREPROC glIsTexture;
PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
PFNGLTEXIMAGE3DPROC glTexImage3D;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLSAMPLECOVERAGEPROC glSampleCoverage;
PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D;
PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
PFNGLPOINTPARAMETERFPROC glPointParameterf;
PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
PFNGLPOINTPARAMETERIPROC glPointParameteri;
PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
PFNGLBLENDCOLORPROC glBlendColor;
PFNGLBLENDEQUATIONPROC glBlendEquation;
PFNGLGENQUERIESPROC glGenQueries;
PFNGLDELETEQUERIESPROC glDeleteQueries;
PFNGLISQUERYPROC glIsQuery;
PFNGLBEGINQUERYPROC glBeginQuery;
PFNGLENDQUERYPROC glEndQuery;
PFNGLGETQUERYIVPROC glGetQueryiv;
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLDELETEBUFFERSPROC glDeleteBuffers;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLISBUFFERPROC glIsBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLBUFFERSUBDATAPROC glBufferSubData;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
PFNGLMAPBUFFERPROC glMapBuffer;
PFNGLUNMAPBUFFERPROC glUnmapBuffer;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC glDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETSHADERSOURCEPROC glGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLGETUNIFORMFVPROC glGetUniformfv;
PFNGLGETUNIFORMIVPROC glGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
PFNGLISPROGRAMPROC glIsProgram;
PFNGLISSHADERPROC glIsShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLUNIFORM4FPROC glUniform4f;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM2IPROC glUniform2i;
PFNGLUNIFORM3IPROC glUniform3i;
PFNGLUNIFORM4IPROC glUniform4i;
PFNGLUNIFORM1FVPROC glUniform1fv;
PFNGLUNIFORM2FVPROC glUniform2fv;
PFNGLUNIFORM3FVPROC glUniform3fv;
PFNGLUNIFORM4FVPROC glUniform4fv;
PFNGLUNIFORM1IVPROC glUniform1iv;
PFNGLUNIFORM2IVPROC glUniform2iv;
PFNGLUNIFORM3IVPROC glUniform3iv;
PFNGLUNIFORM4IVPROC glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
PFNGLCOLORMASKIPROC glColorMaski;
PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
PFNGLENABLEIPROC glEnablei;
PFNGLDISABLEIPROC glDisablei;
PFNGLISENABLEDIPROC glIsEnabledi;
PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
PFNGLBINDBUFFERBASEPROC glBindBufferBase;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
PFNGLCLAMPCOLORPROC glClampColor;
PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender;
PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i;
PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i;
PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i;
PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;
PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
PFNGLGETUNIFORMUIVPROC glGetUniformuiv;
PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
PFNGLUNIFORM1UIPROC glUniform1ui;
PFNGLUNIFORM2UIPROC glUniform2ui;
PFNGLUNIFORM3UIPROC glUniform3ui;
PFNGLUNIFORM4UIPROC glUniform4ui;
PFNGLUNIFORM1UIVPROC glUniform1uiv;
PFNGLUNIFORM2UIVPROC glUniform2uiv;
PFNGLUNIFORM3UIVPROC glUniform3uiv;
PFNGLUNIFORM4UIVPROC glUniform4uiv;
PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;
PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
PFNGLCLEARBUFFERIVPROC glClearBufferiv;
PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
PFNGLCLEARBUFFERFVPROC glClearBufferfv;
PFNGLCLEARBUFFERFIPROC glClearBufferfi;
PFNGLGETSTRINGIPROC glGetStringi;
PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLISVERTEXARRAYPROC glIsVertexArray;
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
PFNGLTEXBUFFERPROC glTexBuffer;
PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex;
PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
PFNGLPROVOKINGVERTEXPROC glProvokingVertex;
PFNGLFENCESYNCPROC glFenceSync;
PFNGLISSYNCPROC glIsSync;
PFNGLDELETESYNCPROC glDeleteSync;
PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
PFNGLWAITSYNCPROC glWaitSync;
PFNGLGETINTEGER64VPROC glGetInteger64v;
PFNGLGETSYNCIVPROC glGetSynciv;
PFNGLGETINTEGER64I_VPROC glGetInteger64i_v;
PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample;
PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample;
PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv;
PFNGLSAMPLEMASKIPROC glSampleMaski;
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex;
PFNGLGENSAMPLERSPROC glGenSamplers;
PFNGLDELETESAMPLERSPROC glDeleteSamplers;
PFNGLISSAMPLERPROC glIsSampler;
PFNGLBINDSAMPLERPROC glBindSampler;
PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;
PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
PFNGLQUERYCOUNTERPROC glQueryCounter;
PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v;
PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v;
PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;
PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui;
PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv;
PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui;
PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv;
PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui;
PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv;
PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui;
PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv;
PFNGLMINSAMPLESHADINGPROC glMinSampleShading;
PFNGLBLENDEQUATIONIPROC glBlendEquationi;
PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;
PFNGLBLENDFUNCIPROC glBlendFunci;
PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei;
PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
PFNGLUNIFORM1DPROC glUniform1d;
PFNGLUNIFORM2DPROC glUniform2d;
PFNGLUNIFORM3DPROC glUniform3d;
PFNGLUNIFORM4DPROC glUniform4d;
PFNGLUNIFORM1DVPROC glUniform1dv;
PFNGLUNIFORM2DVPROC glUniform2dv;
PFNGLUNIFORM3DVPROC glUniform3dv;
PFNGLUNIFORM4DVPROC glUniform4dv;
PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv;
PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv;
PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv;
PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv;
PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv;
PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv;
PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv;
PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv;
PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv;
PFNGLGETUNIFORMDVPROC glGetUniformdv;
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation;
PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex;
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv;
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName;
PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName;
PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv;
PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv;
PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv;
PFNGLPATCHPARAMETERIPROC glPatchParameteri;
PFNGLPATCHPARAMETERFVPROC glPatchParameterfv;
PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback;
PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks;
PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks;
PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback;
PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback;
PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream;
PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed;
PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed;
PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv;
PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
PFNGLSHADERBINARYPROC glShaderBinary;
PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
PFNGLDEPTHRANGEFPROC glDepthRangef;
PFNGLCLEARDEPTHFPROC glClearDepthf;
PFNGLGETPROGRAMBINARYPROC glGetProgramBinary;
PFNGLPROGRAMBINARYPROC glProgramBinary;
PFNGLPROGRAMPARAMETERIPROC glProgramParameteri;
PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages;
PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram;
PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv;
PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline;
PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines;
PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines;
PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline;
PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv;
PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i;
PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv;
PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f;
PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv;
PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d;
PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv;
PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui;
PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv;
PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i;
PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv;
PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f;
PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv;
PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d;
PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv;
PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui;
PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv;
PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i;
PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv;
PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f;
PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv;
PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d;
PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv;
PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui;
PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv;
PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i;
PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv;
PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f;
PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv;
PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d;
PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv;
PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui;
PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv;
PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv;
PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv;
PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv;
PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv;
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv;
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv;
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv;
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv;
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv;
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv;
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv;
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv;
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv;
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv;
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv;
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv;
PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog;
PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d;
PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d;
PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d;
PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d;
PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv;
PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv;
PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv;
PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv;
PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer;
PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv;
PFNGLVIEWPORTARRAYVPROC glViewportArrayv;
PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf;
PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv;
PFNGLSCISSORARRAYVPROC glScissorArrayv;
PFNGLSCISSORINDEXEDPROC glScissorIndexed;
PFNGLSCISSORINDEXEDVPROC glScissorIndexedv;
PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv;
PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed;
PFNGLGETFLOATI_VPROC glGetFloati_v;
PFNGLGETDOUBLEI_VPROC glGetDoublei_v;
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC glDrawArraysInstancedBaseInstance;
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC glDrawElementsInstancedBaseInstance;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC glDrawElementsInstancedBaseVertexBaseInstance;
PFNGLGETINTERNALFORMATIVPROC glGetInternalformativ;
PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC glGetActiveAtomicCounterBufferiv;
PFNGLBINDIMAGETEXTUREPROC glBindImageTexture;
PFNGLMEMORYBARRIERPROC glMemoryBarrier;
PFNGLTEXSTORAGE1DPROC glTexStorage1D;
PFNGLTEXSTORAGE2DPROC glTexStorage2D;
PFNGLTEXSTORAGE3DPROC glTexStorage3D;
PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC glDrawTransformFeedbackInstanced;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC glDrawTransformFeedbackStreamInstanced;
PFNGLCLEARBUFFERDATAPROC glClearBufferData;
PFNGLCLEARBUFFERSUBDATAPROC glClearBufferSubData;
PFNGLDISPATCHCOMPUTEPROC glDispatchCompute;
PFNGLDISPATCHCOMPUTEINDIRECTPROC glDispatchComputeIndirect;
PFNGLCOPYIMAGESUBDATAPROC glCopyImageSubData;
PFNGLFRAMEBUFFERPARAMETERIPROC glFramebufferParameteri;
PFNGLGETFRAMEBUFFERPARAMETERIVPROC glGetFramebufferParameteriv;
PFNGLGETINTERNALFORMATI64VPROC glGetInternalformati64v;
PFNGLINVALIDATETEXSUBIMAGEPROC glInvalidateTexSubImage;
PFNGLINVALIDATETEXIMAGEPROC glInvalidateTexImage;
PFNGLINVALIDATEBUFFERSUBDATAPROC glInvalidateBufferSubData;
PFNGLINVALIDATEBUFFERDATAPROC glInvalidateBufferData;
PFNGLINVALIDATEFRAMEBUFFERPROC glInvalidateFramebuffer;
PFNGLINVALIDATESUBFRAMEBUFFERPROC glInvalidateSubFramebuffer;
PFNGLMULTIDRAWARRAYSINDIRECTPROC glMultiDrawArraysIndirect;
PFNGLMULTIDRAWELEMENTSINDIRECTPROC glMultiDrawElementsIndirect;
PFNGLGETPROGRAMINTERFACEIVPROC glGetProgramInterfaceiv;
PFNGLGETPROGRAMRESOURCEINDEXPROC glGetProgramResourceIndex;
PFNGLGETPROGRAMRESOURCENAMEPROC glGetProgramResourceName;
PFNGLGETPROGRAMRESOURCEIVPROC glGetProgramResourceiv;
PFNGLGETPROGRAMRESOURCELOCATIONPROC glGetProgramResourceLocation;
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC glGetProgramResourceLocationIndex;
PFNGLSHADERSTORAGEBLOCKBINDINGPROC glShaderStorageBlockBinding;
PFNGLTEXBUFFERRANGEPROC glTexBufferRange;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC glTexStorage2DMultisample;
PFNGLTEXSTORAGE3DMULTISAMPLEPROC glTexStorage3DMultisample;
PFNGLTEXTUREVIEWPROC glTextureView;
PFNGLBINDVERTEXBUFFERPROC glBindVertexBuffer;
PFNGLVERTEXATTRIBFORMATPROC glVertexAttribFormat;
PFNGLVERTEXATTRIBIFORMATPROC glVertexAttribIFormat;
PFNGLVERTEXATTRIBLFORMATPROC glVertexAttribLFormat;
PFNGLVERTEXATTRIBBINDINGPROC glVertexAttribBinding;
PFNGLVERTEXBINDINGDIVISORPROC glVertexBindingDivisor;
PFNGLDEBUGMESSAGECONTROLPROC glDebugMessageControl;
PFNGLDEBUGMESSAGEINSERTPROC glDebugMessageInsert;
PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback;
PFNGLGETDEBUGMESSAGELOGPROC glGetDebugMessageLog;
PFNGLPUSHDEBUGGROUPPROC glPushDebugGroup;
PFNGLPOPDEBUGGROUPPROC glPopDebugGroup;
PFNGLOBJECTLABELPROC glObjectLabel;
PFNGLGETOBJECTLABELPROC glGetObjectLabel;
PFNGLOBJECTPTRLABELPROC glObjectPtrLabel;
PFNGLGETOBJECTPTRLABELPROC glGetObjectPtrLabel;
PFNGLBUFFERSTORAGEPROC glBufferStorage;
PFNGLCLEARTEXIMAGEPROC glClearTexImage;
PFNGLCLEARTEXSUBIMAGEPROC glClearTexSubImage;
PFNGLBINDBUFFERSBASEPROC glBindBuffersBase;
PFNGLBINDBUFFERSRANGEPROC glBindBuffersRange;
PFNGLBINDTEXTURESPROC glBindTextures;
PFNGLBINDSAMPLERSPROC glBindSamplers;
PFNGLBINDIMAGETEXTURESPROC glBindImageTextures;
PFNGLBINDVERTEXBUFFERSPROC glBindVertexBuffers;
PFNGLCLIPCONTROLPROC glClipControl;
PFNGLCREATETRANSFORMFEEDBACKSPROC glCreateTransformFeedbacks;
PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC glTransformFeedbackBufferBase;
PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC glTransformFeedbackBufferRange;
PFNGLGETTRANSFORMFEEDBACKIVPROC glGetTransformFeedbackiv;
PFNGLGETTRANSFORMFEEDBACKI_VPROC glGetTransformFeedbacki_v;
PFNGLGETTRANSFORMFEEDBACKI64_VPROC glGetTransformFeedbacki64_v;
PFNGLCREATEBUFFERSPROC glCreateBuffers;
PFNGLNAMEDBUFFERSTORAGEPROC glNamedBufferStorage;
PFNGLNAMEDBUFFERDATAPROC glNamedBufferData;
PFNGLNAMEDBUFFERSUBDATAPROC glNamedBufferSubData;
PFNGLCOPYNAMEDBUFFERSUBDATAPROC glCopyNamedBufferSubData;
PFNGLCLEARNAMEDBUFFERDATAPROC glClearNamedBufferData;
PFNGLCLEARNAMEDBUFFERSUBDATAPROC glClearNamedBufferSubData;
PFNGLMAPNAMEDBUFFERPROC glMapNamedBuffer;
PFNGLMAPNAMEDBUFFERRANGEPROC glMapNamedBufferRange;
PFNGLUNMAPNAMEDBUFFERPROC glUnmapNamedBuffer;
PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC glFlushMappedNamedBufferRange;
PFNGLGETNAMEDBUFFERPARAMETERIVPROC glGetNamedBufferParameteriv;
PFNGLGETNAMEDBUFFERPARAMETERI64VPROC glGetNamedBufferParameteri64v;
PFNGLGETNAMEDBUFFERPOINTERVPROC glGetNamedBufferPointerv;
PFNGLGETNAMEDBUFFERSUBDATAPROC glGetNamedBufferSubData;
PFNGLCREATEFRAMEBUFFERSPROC glCreateFramebuffers;
PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC glNamedFramebufferRenderbuffer;
PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC glNamedFramebufferParameteri;
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC glNamedFramebufferTexture;
PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC glNamedFramebufferTextureLayer;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC glNamedFramebufferDrawBuffer;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC glNamedFramebufferDrawBuffers;
PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC glNamedFramebufferReadBuffer;
PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC glInvalidateNamedFramebufferData;
PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC glInvalidateNamedFramebufferSubData;
PFNGLCLEARNAMEDFRAMEBUFFERIVPROC glClearNamedFramebufferiv;
PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC glClearNamedFramebufferuiv;
PFNGLCLEARNAMEDFRAMEBUFFERFVPROC glClearNamedFramebufferfv;
PFNGLCLEARNAMEDFRAMEBUFFERFIPROC glClearNamedFramebufferfi;
PFNGLBLITNAMEDFRAMEBUFFERPROC glBlitNamedFramebuffer;
PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC glCheckNamedFramebufferStatus;
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC glGetNamedFramebufferParameteriv;
PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetNamedFramebufferAttachmentParameteriv;
PFNGLCREATERENDERBUFFERSPROC glCreateRenderbuffers;
PFNGLNAMEDRENDERBUFFERSTORAGEPROC glNamedRenderbufferStorage;
PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC glNamedRenderbufferStorageMultisample;
PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC glGetNamedRenderbufferParameteriv;
PFNGLCREATETEXTURESPROC glCreateTextures;
PFNGLTEXTUREBUFFERPROC glTextureBuffer;
PFNGLTEXTUREBUFFERRANGEPROC glTextureBufferRange;
PFNGLTEXTURESTORAGE1DPROC glTextureStorage1D;
PFNGLTEXTURESTORAGE2DPROC glTextureStorage2D;
PFNGLTEXTURESTORAGE3DPROC glTextureStorage3D;
PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC glTextureStorage2DMultisample;
PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC glTextureStorage3DMultisample;
PFNGLTEXTURESUBIMAGE1DPROC glTextureSubImage1D;
PFNGLTEXTURESUBIMAGE2DPROC glTextureSubImage2D;
PFNGLTEXTURESUBIMAGE3DPROC glTextureSubImage3D;
PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC glCompressedTextureSubImage1D;
PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC glCompressedTextureSubImage2D;
PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC glCompressedTextureSubImage3D;
PFNGLCOPYTEXTURESUBIMAGE1DPROC glCopyTextureSubImage1D;
PFNGLCOPYTEXTURESUBIMAGE2DPROC glCopyTextureSubImage2D;
PFNGLCOPYTEXTURESUBIMAGE3DPROC glCopyTextureSubImage3D;
PFNGLTEXTUREPARAMETERFPROC glTextureParameterf;
PFNGLTEXTUREPARAMETERFVPROC glTextureParameterfv;
PFNGLTEXTUREPARAMETERIPROC glTextureParameteri;
PFNGLTEXTUREPARAMETERIIVPROC glTextureParameterIiv;
PFNGLTEXTUREPARAMETERIUIVPROC glTextureParameterIuiv;
PFNGLTEXTUREPARAMETERIVPROC glTextureParameteriv;
PFNGLGENERATETEXTUREMIPMAPPROC glGenerateTextureMipmap;
PFNGLBINDTEXTUREUNITPROC glBindTextureUnit;
PFNGLGETTEXTUREIMAGEPROC glGetTextureImage;
PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC glGetCompressedTextureImage;
PFNGLGETTEXTURELEVELPARAMETERFVPROC glGetTextureLevelParameterfv;
PFNGLGETTEXTURELEVELPARAMETERIVPROC glGetTextureLevelParameteriv;
PFNGLGETTEXTUREPARAMETERFVPROC glGetTextureParameterfv;
PFNGLGETTEXTUREPARAMETERIIVPROC glGetTextureParameterIiv;
PFNGLGETTEXTUREPARAMETERIUIVPROC glGetTextureParameterIuiv;
PFNGLGETTEXTUREPARAMETERIVPROC glGetTextureParameteriv;
PFNGLCREATEVERTEXARRAYSPROC glCreateVertexArrays;
PFNGLDISABLEVERTEXARRAYATTRIBPROC glDisableVertexArrayAttrib;
PFNGLENABLEVERTEXARRAYATTRIBPROC glEnableVertexArrayAttrib;
PFNGLVERTEXARRAYELEMENTBUFFERPROC glVertexArrayElementBuffer;
PFNGLVERTEXARRAYVERTEXBUFFERPROC glVertexArrayVertexBuffer;
PFNGLVERTEXARRAYVERTEXBUFFERSPROC glVertexArrayVertexBuffers;
PFNGLVERTEXARRAYATTRIBBINDINGPROC glVertexArrayAttribBinding;
PFNGLVERTEXARRAYATTRIBFORMATPROC glVertexArrayAttribFormat;
PFNGLVERTEXARRAYATTRIBIFORMATPROC glVertexArrayAttribIFormat;
PFNGLVERTEXARRAYATTRIBLFORMATPROC glVertexArrayAttribLFormat;
PFNGLVERTEXARRAYBINDINGDIVISORPROC glVertexArrayBindingDivisor;
PFNGLGETVERTEXARRAYIVPROC glGetVertexArrayiv;
PFNGLGETVERTEXARRAYINDEXEDIVPROC glGetVertexArrayIndexediv;
PFNGLGETVERTEXARRAYINDEXED64IVPROC glGetVertexArrayIndexed64iv;
PFNGLCREATESAMPLERSPROC glCreateSamplers;
PFNGLCREATEPROGRAMPIPELINESPROC glCreateProgramPipelines;
PFNGLCREATEQUERIESPROC glCreateQueries;
PFNGLGETQUERYBUFFEROBJECTI64VPROC glGetQueryBufferObjecti64v;
PFNGLGETQUERYBUFFEROBJECTIVPROC glGetQueryBufferObjectiv;
PFNGLGETQUERYBUFFEROBJECTUI64VPROC glGetQueryBufferObjectui64v;
PFNGLGETQUERYBUFFEROBJECTUIVPROC glGetQueryBufferObjectuiv;
PFNGLMEMORYBARRIERBYREGIONPROC glMemoryBarrierByRegion;
PFNGLGETTEXTURESUBIMAGEPROC glGetTextureSubImage;
PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC glGetCompressedTextureSubImage;
PFNGLGETGRAPHICSRESETSTATUSPROC glGetGraphicsResetStatus;
PFNGLGETNCOMPRESSEDTEXIMAGEPROC glGetnCompressedTexImage;
PFNGLGETNTEXIMAGEPROC glGetnTexImage;
PFNGLGETNUNIFORMDVPROC glGetnUniformdv;
PFNGLGETNUNIFORMFVPROC glGetnUniformfv;
PFNGLGETNUNIFORMIVPROC glGetnUniformiv;
PFNGLGETNUNIFORMUIVPROC glGetnUniformuiv;
PFNGLREADNPIXELSPROC glReadnPixels;
PFNGLTEXTUREBARRIERPROC glTextureBarrier;